[phases.setup]
nixPkgs = ['...', 'php82', 'php82Extensions.mysqli', 'php82Extensions.pdo', 'php82Extensions.pdo_mysql']

[phases.build]
cmds = ['echo "No build step required for PHP"']

[start]
cmd = 'php -S 0.0.0.0:$PORT -t .'
